Implement task #3
ozonva/ova-competition-api pull request #3
Opened 2021-08-17 14:11 UTC by SukharevAndrey

Add participants and corresponding stuff

2021-08-17 17:33 UTC, kshmatov requested changes

2021-08-17 17:33 UTC, kshmatov commented on internal/utils/config.go
> +
Не надо делать большие вложенные функции, это не очень go-way. Обычно если получается больше 3-4 строк, то стоит вынести все в полноценную функцию и не усложнять код.

А тут и строк много и логика какая-то присутствует.

2021-08-17 17:44 UTC, SukharevAndrey commented on internal/utils/config.go
> +
Выделил в отдельную функцию

2021-08-18 10:00 UTC, kshmatov approved these changes

2021-08-23 20:15 UTC, merged